# This Dockerfile tests the hack/Makefile output against git2go.
ARG BASE_VARIANT=bullseye
ARG GO_VERSION=1.17.6
ARG XX_VERSION=1.1.0

FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx

FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-${BASE_VARIANT} as gostable

FROM gostable AS go-linux

FROM go-${TARGETOS} AS build-base-bullseye

COPY --from=xx / /

# Align golang base image with bookworm. 
# TODO: Replace this with a golang bookworm variant, once it is released.
RUN echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list.d/bookworm.list \
	&& echo "deb-src http://deb.debian.org/debian bookworm main" /etc/apt/sources.list.d/bookworm.list \
	&& xx-apt update \
	&& xx-apt -t bookworm upgrade -y

COPY ./hack/Makefile /libgit2/Makefile

RUN make -C /libgit2/ cmake

ARG TARGETPLATFORM
RUN make -C /libgit2/ dependencies

FROM build-base-${BASE_VARIANT} as libgit2-bullseye

ARG TARGETPLATFORM
RUN FLAGS=$(xx-clang --print-cmake-defines) make -C /libgit2/ libgit2

FROM libgit2-${BASE_VARIANT} as test-bullseye

# Cache clone
ARG GIT2GO_TAG
RUN git config --global advice.detachedHead false \
    && git clone --depth=1 --branch=${GIT2GO_TAG} https://github.com/libgit2/git2go /git2go \
    && cd /git2go \
    && go mod tidy

# Set workdir
WORKDIR /git2go

# Run tests
ARG TARGETPLATFORM
ARG CACHE_BUST
RUN set -eux; \
    echo "=> Dynamic test at $CACHE_BUST for $TARGETPLATFORM" \
    && CGO_ENABLED=1 xx-go run script/check-MakeGitError-thread-lock.go \
    && CGO_ENABLED=1 xx-go test ./...
